-- ============================================================================
-- SQL Migration: V2__Specialty_Clinics_Schema.sql
-- Description: Core schema design for 8 specialty clinical diagnostics modules.
-- Co-references: consultations(id), patients(id), visits(id).
-- ============================================================================

-- 1. Medicine / Internal Medicine
CREATE TABLE clinic_medicine (
    consultation_id UUID PRIMARY KEY REFERENCES consultations(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES patients(id),
    visit_id UUID NOT NULL REFERENCES visits(id),
    systolic_bp INT,
    diastolic_bp INT,
    heart_rate INT,
    respiratory_rate INT,
    temperature_celsius NUMERIC(4,2),
    oxygen_saturation INT,
    blood_glucose_fasting NUMERIC(5,2),
    blood_glucose_random NUMERIC(5,2),
    ros_constitutional BOOLEAN DEFAULT FALSE,
    ros_ent BOOLEAN DEFAULT FALSE,
    ros_cardiovascular BOOLEAN DEFAULT FALSE,
    ros_respiratory BOOLEAN DEFAULT FALSE,
    ros_gastrointestinal BOOLEAN DEFAULT FALSE,
    ros_musculoskeletal BOOLEAN DEFAULT FALSE,
    ros_neurological BOOLEAN DEFAULT FALSE,
    pe_general TEXT,
    pe_cardiovascular TEXT,
    pe_respiratory TEXT,
    pe_abdominal TEXT,
    pe_neurological TEXT,
    pre_op_clearance BOOLEAN DEFAULT FALSE,
    clearance_notes TEXT,
    ecg_findings TEXT,
    chest_xray_findings TEXT,
    follow_up_interval_days INTEGER,
    ordered_labs JSONB DEFAULT '[]',
    ordered_imaging JSONB DEFAULT '[]',
    prescribed_medications JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Ear, Nose & Throat (ENT)
CREATE TABLE clinic_ent (
    consultation_id UUID PRIMARY KEY REFERENCES consultations(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES patients(id),
    visit_id UUID NOT NULL REFERENCES visits(id),
    otoscopy_right_normal BOOLEAN DEFAULT TRUE,
    otoscopy_right_findings TEXT,
    otoscopy_left_normal BOOLEAN DEFAULT TRUE,
    otoscopy_left_findings TEXT,
    tympanic_membrane TEXT,
    hearing_test_type VARCHAR(100),
    air_conduction_right TEXT,
    air_conduction_left TEXT,
    bone_conduction_right TEXT,
    bone_conduction_left TEXT,
    tympanometry_right TEXT,
    tympanometry_left TEXT,
    hearing_impairment_type VARCHAR(100),
    nasal_septum TEXT,
    turbinates TEXT,
    nasal_mucosa TEXT,
    sinus_tenderness TEXT,
    oropharynx_exam TEXT,
    larynx_exam TEXT,
    voice_assessment TEXT,
    fistula_test TEXT,
    weber_test TEXT,
    rinne_test_right TEXT,
    rinne_test_left TEXT,
    follow_up_interval_days INTEGER,
    ordered_labs JSONB DEFAULT '[]',
    ordered_imaging JSONB DEFAULT '[]',
    prescribed_medications JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Dental
CREATE TABLE clinic_dental (
    consultation_id UUID PRIMARY KEY REFERENCES consultations(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES patients(id),
    visit_id UUID NOT NULL REFERENCES visits(id),
    odontogram JSONB DEFAULT '[]', -- Array of { tooth_num, status, surfaces, treatment }
    gingivitis BOOLEAN DEFAULT FALSE,
    periodontitis BOOLEAN DEFAULT FALSE,
    pocket_depth_max_mm INT,
    bleeding_on_probing BOOLEAN DEFAULT FALSE,
    mobility_grade VARCHAR(20),
    oral_lesions TEXT,
    mucosal_exam TEXT,
    tongue_exam TEXT,
    salivary_glands TEXT,
    xray_type VARCHAR(100),
    xray_findings TEXT,
    impacted_teeth JSONB DEFAULT '[]',
    diagnosis TEXT,
    treatment_plan TEXT,
    procedure_code VARCHAR(50),
    procedure_description TEXT,
    follow_up_interval_days INTEGER,
    ordered_labs JSONB DEFAULT '[]',
    ordered_imaging JSONB DEFAULT '[]',
    prescribed_medications JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Retina
CREATE TABLE clinic_retina (
    consultation_id UUID PRIMARY KEY REFERENCES consultations(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES patients(id),
    visit_id UUID NOT NULL REFERENCES visits(id),
    dilation_achieved BOOLEAN DEFAULT FALSE,
    dilation_agent VARCHAR(100),
    dilation_time TIMESTAMPTZ,
    fundus_view_quality VARCHAR(50),
    vitreous TEXT,
    optic_disc_right TEXT,
    optic_disc_left TEXT,
    macula_right TEXT,
    macula_left TEXT,
    retina_vessels_right TEXT,
    retina_vessels_left TEXT,
    periphery_right TEXT,
    periphery_left TEXT,
    oct_performed BOOLEAN DEFAULT FALSE,
    oct_right_cst_microns INT,
    oct_left_cst_microns INT,
    oct_right_findings TEXT,
    oct_left_findings TEXT,
    oct_image_urls JSONB DEFAULT '[]',
    fundus_photos JSONB DEFAULT '[]',
    angiography_performed BOOLEAN DEFAULT FALSE,
    angiography_findings TEXT,
    angiography_image_urls JSONB DEFAULT '[]',
    retinopathy_type VARCHAR(100),
    macular_pathology VARCHAR(100),
    diabetic_retinopathy_stage VARCHAR(100),
    amd_type VARCHAR(100),
    intravitreal_injection BOOLEAN DEFAULT FALSE,
    injection_agent VARCHAR(100),
    laser_performed BOOLEAN DEFAULT FALSE,
    laser_type VARCHAR(100),
    surgery_recommended BOOLEAN DEFAULT FALSE,
    surgery_type VARCHAR(200),
    follow_up_interval_days INTEGER,
    ordered_labs JSONB DEFAULT '[]',
    ordered_imaging JSONB DEFAULT '[]',
    prescribed_medications JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Glaucoma
CREATE TABLE clinic_glaucoma (
    consultation_id UUID PRIMARY KEY REFERENCES consultations(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES patients(id),
    visit_id UUID NOT NULL REFERENCES visits(id),
    iop_right_mmhg NUMERIC(4,2) CHECK (iop_right_mmhg >= 0 AND iop_right_mmhg <= 80),
    iop_left_mmhg NUMERIC(4,2) CHECK (iop_left_mmhg >= 0 AND iop_left_mmhg <= 80),
    iop_measurement_time TIMESTAMPTZ,
    iop_method VARCHAR(50), -- Goldmann, Tonopen, iCare, NCT, Pneumatonometry
    pachymetry_right_microns INT CHECK (pachymetry_right_microns >= 300 AND pachymetry_right_microns <= 700),
    pachymetry_left_microns INT CHECK (pachymetry_left_microns >= 300 AND pachymetry_left_microns <= 700),
    pachymetry_adjusted_iop_right NUMERIC(4,2),
    pachymetry_adjusted_iop_left NUMERIC(4,2),
    gonioscopy_right TEXT,
    gonioscopy_left TEXT,
    angle_recession_right TEXT,
    angle_recession_left TEXT,
    neovascularization_right BOOLEAN DEFAULT FALSE,
    neovascularization_left BOOLEAN DEFAULT FALSE,
    cd_ratio_right NUMERIC(3,2) CHECK (cd_ratio_right >= 0.0 AND cd_ratio_right <= 1.50),
    cd_ratio_left NUMERIC(3,2) CHECK (cd_ratio_left >= 0.0 AND cd_ratio_left <= 1.50),
    neuroretinal_rim_right TEXT,
    neuroretinal_rim_left TEXT,
    disc_hemorrhage_right BOOLEAN DEFAULT FALSE,
    disc_hemorrhage_left BOOLEAN DEFAULT FALSE,
    nerve_fiber_layer_defect_right BOOLEAN DEFAULT FALSE,
    nerve_fiber_layer_defect_left BOOLEAN DEFAULT FALSE,
    vf_performed BOOLEAN DEFAULT FALSE,
    vf_right_md NUMERIC(5,2),
    vf_left_md NUMERIC(5,2),
    vf_right_psd NUMERIC(5,2),
    vf_left_psd NUMERIC(5,2),
    vf_right_pattern TEXT,
    vf_left_pattern TEXT,
    vf_reliability_right VARCHAR(50),
    vf_reliability_left VARCHAR(50),
    oct_rnfl_performed BOOLEAN DEFAULT FALSE,
    oct_rnfl_right_avg_microns INT,
    oct_rnfl_left_avg_microns INT,
    oct_rnfl_image_urls JSONB DEFAULT '[]',
    glaucoma_type VARCHAR(100), -- POAG, PACG, PXFG, Pigmentary, Secondary, Normal Tension
    staging VARCHAR(50), -- Mild, Moderate, Severe, End-Stage
    target_iop_right INT,
    target_iop_left INT,
    current_drops JSONB DEFAULT '[]',
    laser_performed BOOLEAN DEFAULT FALSE,
    laser_type VARCHAR(100), -- ALT, SLT, LPI, CPC
    surgery_recommended BOOLEAN DEFAULT FALSE,
    surgery_type VARCHAR(200), -- Trabeculectomy, Tube Shunt, MIGS, Goniotomy
    follow_up_interval_days INTEGER,
    ordered_labs JSONB DEFAULT '[]',
    ordered_imaging JSONB DEFAULT '[]',
    prescribed_medications JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Orbit / Oculoplastics
CREATE TABLE clinic_orbit (
    consultation_id UUID PRIMARY KEY REFERENCES consultations(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES patients(id),
    visit_id UUID NOT NULL REFERENCES visits(id),
    mrd1_right_mm NUMERIC(4,2),
    mrd1_left_mm NUMERIC(4,2),
    mrd2_right_mm NUMERIC(4,2),
    mrd2_left_mm NUMERIC(4,2),
    lf_width_right_mm NUMERIC(4,2),
    lf_width_left_mm NUMERIC(4,2),
    ptosis_right BOOLEAN DEFAULT FALSE,
    ptosis_left BOOLEAN DEFAULT FALSE,
    levator_function_right TEXT,
    levator_function_left TEXT,
    bells_phenomenon VARCHAR(50),
    lid_margin_right TEXT,
    lid_margin_left TEXT,
    entropion_ectropion_trichiasis_right TEXT,
    entropion_ectropion_trichiasis_left TEXT,
    lid_mass_right TEXT,
    lid_mass_left TEXT,
    blepharospasm BOOLEAN DEFAULT FALSE,
    tear_meniscus_height NUMERIC(4,2),
    nlf_dt TEXT,
    dacryocystitis BOOLEAN DEFAULT FALSE,
    lacrimal_irrigation TEXT,
    schirmer_right_mm INT,
    schirmer_left_mm INT,
    proptosis_right_mm NUMERIC(4,2),
    proptosis_left_mm NUMERIC(4,2),
    hertel_base_mm NUMERIC(4,2),
    enophthalmos_right_mm NUMERIC(4,2),
    enophthalmos_left_mm NUMERIC(4,2),
    orbital_mass BOOLEAN DEFAULT FALSE,
    orbital_mass_location TEXT,
    extraocular_movements TEXT,
    ted_active BOOLEAN DEFAULT FALSE,
    ted_cas_score INT CHECK (ted_cas_score >= 0 AND ted_cas_score <= 10),
    ted_eugogo_class VARCHAR(50),
    surgery_recommended BOOLEAN DEFAULT FALSE,
    surgery_type VARCHAR(200),
    follow_up_interval_days INTEGER,
    ordered_labs JSONB DEFAULT '[]',
    ordered_imaging JSONB DEFAULT '[]',
    prescribed_medications JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Pediatrics & Strabismus
CREATE TABLE clinic_pediatrics (
    consultation_id UUID PRIMARY KEY REFERENCES consultations(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES patients(id),
    visit_id UUID NOT NULL REFERENCES visits(id),
    gestational_age_weeks INT CHECK (gestational_age_weeks >= 24 AND gestational_age_weeks <= 42),
    birth_weight_grams INT,
    developmental_milestones TEXT,
    va_method VARCHAR(50), -- LEA Symbols, Teller Acuity, HOTV, Snellen, LogMAR
    va_right VARCHAR(20),
    va_left VARCHAR(20),
    va_binocular VARCHAR(20),
    cycloplegia_achieved BOOLEAN DEFAULT FALSE,
    refraction_agent VARCHAR(50), -- Cyclopentolate, Atropine
    refraction_right_sph NUMERIC(5,2),
    refraction_right_cyl NUMERIC(5,2),
    refraction_right_axis INT,
    refraction_left_sph NUMERIC(5,2),
    refraction_left_cyl NUMERIC(5,2),
    refraction_left_axis INT,
    deviation_type VARCHAR(50), -- Esotropia, Exotropia, Hypertropia, Hypotropia
    deviation_constant BOOLEAN DEFAULT FALSE,
    deviation_distance_near_pd VARCHAR(50),
    cover_test_distance TEXT,
    cover_test_near TEXT,
    prism_cover_test TEXT,
    ductions_right TEXT,
    ductions_left TEXT,
    versions TEXT,
    head_posture TEXT,
    nystagmus TEXT,
    worth_4_dot TEXT,
    stereoacuity_seconds INT,
    bagolini_glasses TEXT,
    amsler_grid TEXT,
    slit_lamp_findings TEXT,
    fundus_findings TEXT,
    rop_screening BOOLEAN DEFAULT FALSE,
    rop_stage VARCHAR(50),
    amblyopia_present BOOLEAN DEFAULT FALSE,
    amblyopia_type VARCHAR(50), -- Strabismic, Refractive, Deprivation
    amblyopia_eye VARCHAR(10),
    patching_hours_per_day INT,
    occlusion_therapy TEXT,
    atropine_penalization TEXT,
    glasses_prescribed BOOLEAN DEFAULT FALSE,
    surgery_recommended BOOLEAN DEFAULT FALSE,
    surgery_type VARCHAR(200), -- Strabismus, ROP laser
    follow_up_interval_days INTEGER,
    ordered_labs JSONB DEFAULT '[]',
    ordered_imaging JSONB DEFAULT '[]',
    prescribed_medications JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. General Ophthalmology
CREATE TABLE clinic_general_ophth (
    consultation_id UUID PRIMARY KEY REFERENCES consultations(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES patients(id),
    visit_id UUID NOT NULL REFERENCES visits(id),
    va_uncorrected_right VARCHAR(20),
    va_uncorrected_left VARCHAR(20),
    va_corrected_right VARCHAR(20),
    va_corrected_left VARCHAR(20),
    va_pinhole_right VARCHAR(20),
    va_pinhole_left VARCHAR(20),
    va_method VARCHAR(50), -- Snellen, LogMAR
    refraction_right_sph NUMERIC(5,2),
    refraction_right_cyl NUMERIC(5,2),
    refraction_right_axis INT,
    refraction_left_sph NUMERIC(5,2),
    refraction_left_cyl NUMERIC(5,2),
    refraction_left_axis INT,
    add_power NUMERIC(4,2),
    lids_lashes_right TEXT,
    lids_lashes_left TEXT,
    conjunctiva_sclera_right TEXT,
    conjunctiva_sclera_left TEXT,
    cornea_right TEXT,
    cornea_left TEXT,
    anterior_chamber_right TEXT,
    anterior_chamber_left TEXT,
    iris_right TEXT,
    iris_left TEXT,
    lens_right TEXT,
    lens_left TEXT,
    iop_right_mmhg NUMERIC(4,2),
    iop_left_mmhg NUMERIC(4,2),
    iop_method VARCHAR(50),
    dilation_performed BOOLEAN DEFAULT FALSE,
    vitreous_right TEXT,
    vitreous_left TEXT,
    optic_disc_right TEXT,
    optic_disc_left TEXT,
    macula_right TEXT,
    macula_left TEXT,
    vessels_right TEXT,
    vessels_left TEXT,
    periphery_right TEXT,
    periphery_left TEXT,
    working_diagnosis TEXT,
    differential_diagnosis TEXT,
    management_plan TEXT,
    glasses_prescribed BOOLEAN DEFAULT FALSE,
    glasses_rx JSONB DEFAULT '[]',
    surgery_recommended BOOLEAN DEFAULT FALSE,
    surgery_type VARCHAR(200),
    follow_up_interval_days INTEGER,
    ordered_labs JSONB DEFAULT '[]',
    ordered_imaging JSONB DEFAULT '[]',
    prescribed_medications JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
